[versions]
# libraries
spring-boot = "3.5.8"
cosid = "2.15.1"
wow = "6.6.0"
coapi = "1.12.8"
cocache = "3.10.5"
cosec = "3.2.2"
cosky = "4.9.8"
simba = "2.9.6"
guava = "33.5.0-jre"
kotlin-logging = "7.0.13"
swagger = "2.2.41"
springdoc = "2.8.14"
# test
junit = "5.14.1"
fluent-assert = "0.2.5"
mockk = "1.14.6"
# plugins
kotlin = "2.2.21"
ksp = "2.3.3"
dokka = "2.1.0"
detekt = "1.23.8"
publish-plugin = "2.0.0"
kover = "0.9.3"
test-retry = "1.6.4"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
cosid-bom = { module = "me.ahoo.cosid:cosid-bom", version.ref = "cosid" }
wow-bom = { module = "me.ahoo.wow:wow-bom", version.ref = "wow" }
coapi-bom = { module = "me.ahoo.coapi:coapi-bom", version.ref = "coapi" }
cocache-bom = { module = "me.ahoo.cocache:cocache-bom", version.ref = "cocache" }
cosec-bom = { module = "me.ahoo.cosec:cosec-bom", version.ref = "cosec" }
cosky-bom = { module = "me.ahoo.cosky:cosky-bom", version.ref = "cosky" }
simba-bom = { module = "me.ahoo.simba:simba-bom", version.ref = "simba" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swagger" }
springdoc-bom = { module = "org.springdoc:springdoc-openapi-bom", version.ref = "springdoc" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
fluent-assert-bom = { module = "me.ahoo.test:fluent-assert-bom", version.ref = "fluent-assert" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }
test-retry = { id = "org.gradle.test-retry", version.ref = "test-retry" }

